/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "plfkgfxycgtphwhrzcpz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsZmtnZnh5Y2d0cGh3aHJ6Y3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NzgwNTcsImV4cCI6MjA4NjA1NDA1N30.B4qYRLZ8g9WbZZubBGJnt1w9-lkDQTu-yJz6cXgr21o"